apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-load-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-load-mongodb
  template:
    metadata:
      labels:
        app: demo-app-load-mongodb
    spec:
      containers:
      - name: demo-app-load-mongodb
        image: dbazhenov/demo_app_load:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
        envFrom:
        - configMapRef:
            name: demo-app-config
        - secretRef:
            name: demo-app-secret
        env:
        - name: LOAD_MYSQL
          value: "false"
        - name: LOAD_POSTGRES
          value: "false"
        - name: LOAD_MONGODB
          value: "true"
