apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-dataset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-dataset
  template:
    metadata:
      labels:
        app: demo-app-dataset
    spec:
      containers:
      - name: demo-app-dataset
        image: dbazhenov/demo_app_dataset:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "3Gi"
            cpu: "1"
          limits:
            memory: "3Gi"
            cpu: "1"
        envFrom:
        - configMapRef:
            name: demo-app-config
        - secretRef:
            name: demo-app-secret
        env:
        - name: DEBUG
          value: "false"
