apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-web
  annotations:
    kubernetes.io/change-cause: "Update to latest image"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-web
  template:
    metadata:
      labels:
        app: demo-app-web
      annotations:
        kubernetes.io/change-cause: "Update to latest image"
    spec:
      containers:
      - name: demo-app-web
        image: dbazhenov/demo_app_web:0.1.7
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: demo-app-config
        - secretRef:
            name: demo-app-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-web-service
spec:
  selector:
    app: demo-app-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
