name: demo-app
debug: "false"

# Dataset import configuration
# Options for datasetLoadType:
# - csv: Load data from CSV files.
# - github: Get data from the GitHub API and write to the database in portions for each repository.
datasetLoadType: "csv" # Options: csv, github

# Delay between data imports and updates, in minutes. Useful if the number of requests to the GitHub API is limited.
delayMinutes: "10"

# Parameters for loading a dataset from the GitHub API.
# Required if datasetLoadType is set to github.
githubToken: "" # Required parameter, get it from https://github.com/settings/tokens
githubOrg: "percona"

# Path to files with demo data to load from CSV files.
# Required if datasetLoadType is set to csv.
datasetDemoPullsCSV: "https://github.com/dbazhenov/github-stat/raw/refs/heads/main/data/csv/pulls.csv.zip"
datasetDemoReposCSV: "https://github.com/dbazhenov/github-stat/raw/refs/heads/main/data/csv/repositories.csv.zip"

replicaCount:
  dataset: 1
  load: 1

images:
  web:
    repository: dbazhenov/demo_app_web
    pullPolicy: Always
    tag: "0.1.4"
  dataset:
    repository: dbazhenov/demo_app_dataset
    pullPolicy: Always
    tag: "0.1.4"
  load:
    repository: dbazhenov/demo_app_load
    pullPolicy: Always
    tag: "0.1.4"
  valkey:
    repository: valkey/valkey
    pullPolicy: Always
    tag: "8"

controlPanelService:
  type: LoadBalancer  # LoadBalancer or NodePort 
  nodePort: 3001
  port: 80
  targetPort: 3001 # controlPanelPort - CONTROL_PANEL_PORT

useResourceLimits: true

resources:
  web:
    requests:
      memory: "1Gi"
      cpu: "600m"
    limits:
      memory: "1Gi"
      cpu: "600m"
  dataset:
    requests:
      memory: "6Gi"
      cpu: "1"
    limits:
      memory: "6Gi"
      cpu: "1"
  load:
    requests:
      memory: "2Gi"
      cpu: "3"
    limits:
      memory: "2Gi"
      cpu: "3"
  valkey:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "1"

# Configurations for different instances
separateLoads: false
loadEnvironments:
  - name: mysql
    env:
      - name: LOAD_MYSQL
        value: "true"
      - name: LOAD_POSTGRES
        value: "false"
      - name: LOAD_MONGODB
        value: "false"
  - name: postgres
    env:
      - name: LOAD_MYSQL
        value: "false"
      - name: LOAD_POSTGRES
        value: "true"
      - name: LOAD_MONGODB
        value: "false"
  - name: mongodb
    env:
      - name: LOAD_MYSQL
        value: "false"
      - name: LOAD_POSTGRES
        value: "false"
      - name: LOAD_MONGODB
        value: "true"

# Secret data
valkeyPassword: ""

# Configurations for the application
valkeyAddr: "demo-app-valkey-service"
valkeyPort: "6379"
valkeyDB: "0"
valkeyAllowEmptyPassword: "yes"
